[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.19"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
local = "http://localhost:8545"

[etherscan_api]
mainnet = "${ETHERSCAN_API_KEY}"
sepolia = "${ETHERSCAN_API_KEY}" 