name: Build

on:
  workflow_call:
    inputs:
      bun-version:
        required: false
        type: string
        default: '1.2.18'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ inputs.bun-version }}

      - name: Install dependencies
        run: bun install

      - name: Setup project
        run: bun setup

      - name: Build package
        run: bun run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            dist/
            package.json
            package-lock.json
            bun.lockb
          retention-days: 1
