name: Node.js Package

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.8
      - run: bun install
      - run: bun setup
      - run: bun run build
      - run: bun publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.LAGOON_RELEASER}}

